In [ ]:
import numpy as np
import itertools

In [ ]:
p = np.array([np.sqrt(1/2), np.sqrt(1/2)])              #plus   =A1
m = np.array([np.sqrt(1/2), -np.sqrt(1/2)])             #minus  =A2
pi = np.array([np.sqrt(1/2), 1j*np.sqrt(1/2)])          #plus_i =A3
mi = np.array([np.sqrt(1/2), -1j*np.sqrt(1/2)])        #minus_i =A4


In [ ]:
print(p,m,pi,mi, sep="\n")

[0.70710678 0.70710678]
[ 0.70710678 -0.70710678]
[0.70710678+0.j         0.        +0.70710678j]
[0.70710678+0.j         0.        -0.70710678j]


In [ ]:
combination=[]
for i1 in [p,m,pi,mi]:
  for i2 in [p,m,pi,mi]:
    for i3 in [p,m,pi,mi]:
      combination.append([i1,i2,i3])

In [ ]:
len(combination)
combination


[[array([0.70710678, 0.70710678]),
  array([0.70710678, 0.70710678]),
  array([0.70710678, 0.70710678])],
 [array([0.70710678, 0.70710678]),
  array([0.70710678, 0.70710678]),
  array([ 0.70710678, -0.70710678])],
 [array([0.70710678, 0.70710678]),
  array([0.70710678, 0.70710678]),
  array([0.70710678+0.j        , 0.        +0.70710678j])],
 [array([0.70710678, 0.70710678]),
  array([0.70710678, 0.70710678]),
  array([0.70710678+0.j        , 0.        -0.70710678j])],
 [array([0.70710678, 0.70710678]),
  array([ 0.70710678, -0.70710678]),
  array([0.70710678, 0.70710678])],
 [array([0.70710678, 0.70710678]),
  array([ 0.70710678, -0.70710678]),
  array([ 0.70710678, -0.70710678])],
 [array([0.70710678, 0.70710678]),
  array([ 0.70710678, -0.70710678]),
  array([0.70710678+0.j        , 0.        +0.70710678j])],
 [array([0.70710678, 0.70710678]),
  array([ 0.70710678, -0.70710678]),
  array([0.70710678+0.j        , 0.        -0.70710678j])],
 [array([0.70710678, 0.70710678]),
  array([

In [ ]:
#-------------   |X>   ---------------------------
X=[]
for i in combination:
  temp1=np.tensordot(i[0],i[1],axes=0).flatten()
  temp2=np.tensordot(temp1,i[2],axes=0).flatten()
  X.append(temp2[np.newaxis].T)


print(temp2[np.newaxis].T)       # 8 coloumns 1 row
print(temp2[np.newaxis].T.shape) # row matrix of size (8 X 1)


[[ 0.35355339+0.j        ]
 [ 0.        -0.35355339j]
 [ 0.        -0.35355339j]
 [-0.35355339+0.j        ]
 [ 0.        -0.35355339j]
 [-0.35355339+0.j        ]
 [-0.35355339+0.j        ]
 [ 0.        +0.35355339j]]
(8, 1)


In [ ]:
X

[array([[0.35355339],
        [0.35355339],
        [0.35355339],
        [0.35355339],
        [0.35355339],
        [0.35355339],
        [0.35355339],
        [0.35355339]]),
 array([[ 0.35355339],
        [-0.35355339],
        [ 0.35355339],
        [-0.35355339],
        [ 0.35355339],
        [-0.35355339],
        [ 0.35355339],
        [-0.35355339]]),
 array([[0.35355339+0.j        ],
        [0.        +0.35355339j],
        [0.35355339+0.j        ],
        [0.        +0.35355339j],
        [0.35355339+0.j        ],
        [0.        +0.35355339j],
        [0.35355339+0.j        ],
        [0.        +0.35355339j]]),
 array([[0.35355339+0.j        ],
        [0.        -0.35355339j],
        [0.35355339+0.j        ],
        [0.        -0.35355339j],
        [0.35355339+0.j        ],
        [0.        -0.35355339j],
        [0.35355339+0.j        ],
        [0.        -0.35355339j]]),
 array([[ 0.35355339],
        [ 0.35355339],
        [-0.35355339],
        [-0.3535533

In [ ]:
np.array([[X[0][0][0],X[0][1][0]],[X[0][2][0],X[0][3][0]],[X[0][4][0],X[0][5][0]],[X[0][6][0],X[0][7][0]]])

array([[0.35355339, 0.35355339],
       [0.35355339, 0.35355339],
       [0.35355339, 0.35355339],
       [0.35355339, 0.35355339]])

In [ ]:
List = []
for i in range(64):
  List.append(np.array([[X[i][0][0],X[i][1][0]],[X[i][2][0],X[i][3][0]],[X[i][4][0],X[i][5][0]],[X[i][6][0],X[i][7][0]]]))
  Z = np.array(List)

print(Z)


[[[ 0.35355339+0.j          0.35355339+0.j        ]
  [ 0.35355339+0.j          0.35355339+0.j        ]
  [ 0.35355339+0.j          0.35355339+0.j        ]
  [ 0.35355339+0.j          0.35355339+0.j        ]]

 [[ 0.35355339+0.j         -0.35355339+0.j        ]
  [ 0.35355339+0.j         -0.35355339+0.j        ]
  [ 0.35355339+0.j         -0.35355339+0.j        ]
  [ 0.35355339+0.j         -0.35355339+0.j        ]]

 [[ 0.35355339+0.j          0.        +0.35355339j]
  [ 0.35355339+0.j          0.        +0.35355339j]
  [ 0.35355339+0.j          0.        +0.35355339j]
  [ 0.35355339+0.j          0.        +0.35355339j]]

 [[ 0.35355339+0.j          0.        -0.35355339j]
  [ 0.35355339+0.j          0.        -0.35355339j]
  [ 0.35355339+0.j          0.        -0.35355339j]
  [ 0.35355339+0.j          0.        -0.35355339j]]

 [[ 0.35355339+0.j          0.35355339+0.j        ]
  [-0.35355339+0.j         -0.35355339+0.j        ]
  [ 0.35355339+0.j          0.35355339+0.j        ]
  [-

In [ ]:
Z[0]

array([[0.35355339+0.j, 0.35355339+0.j],
       [0.35355339+0.j, 0.35355339+0.j],
       [0.35355339+0.j, 0.35355339+0.j],
       [0.35355339+0.j, 0.35355339+0.j]])

In [ ]:
Z[0][0]

array([0.35355339+0.j, 0.35355339+0.j])

In [ ]:
np.dot(Z[0][0],np.conjugate(Z[0][0]))

(0.2500000000000001+0j)

In [ ]:
Z[0][1]

array([0.35355339+0.j, 0.35355339+0.j])

In [ ]:
np.dot(Z[0],np.conjugate(Z[0]).T)

array([[0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j],
       [0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j],
       [0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j],
       [0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j]])

In [ ]:
np.dot(Z[1],np.conjugate(Z[1]).T)

array([[0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j],
       [0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j],
       [0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j],
       [0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j]])

In [ ]:
Z[62]

array([[ 0.35355339+0.j        ,  0.        +0.35355339j],
       [ 0.        -0.35355339j,  0.35355339+0.j        ],
       [ 0.        -0.35355339j,  0.35355339+0.j        ],
       [-0.35355339+0.j        ,  0.        -0.35355339j]])

In [ ]:
np.dot(Z[62],np.conjugate(Z[62]).T)

array([[ 0.25+0.j  ,  0.  +0.25j,  0.  +0.25j, -0.25+0.j  ],
       [ 0.  -0.25j,  0.25+0.j  ,  0.25+0.j  ,  0.  +0.25j],
       [ 0.  -0.25j,  0.25+0.j  ,  0.25+0.j  ,  0.  +0.25j],
       [-0.25+0.j  ,  0.  -0.25j,  0.  -0.25j,  0.25+0.j  ]])

In [ ]:
sum = np.zeros((4,4))
sum

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
sum = np.zeros((4,4))
for i in range(64):
  sum = sum + np.dot(Z[i],np.conjugate(Z[i]).T)
sum

array([[1.6000000e+01+0.0000000e+00j, 0.0000000e+00+0.0000000e+00j,
        4.4408921e-16-4.4408921e-16j, 0.0000000e+00+0.0000000e+00j],
       [0.0000000e+00+0.0000000e+00j, 1.6000000e+01+0.0000000e+00j,
        0.0000000e+00+0.0000000e+00j, 4.4408921e-16-4.4408921e-16j],
       [4.4408921e-16+4.4408921e-16j, 0.0000000e+00+0.0000000e+00j,
        1.6000000e+01+0.0000000e+00j, 0.0000000e+00+0.0000000e+00j],
       [0.0000000e+00+0.0000000e+00j, 4.4408921e-16+4.4408921e-16j,
        0.0000000e+00+0.0000000e+00j, 1.6000000e+01+0.0000000e+00j]])

In [ ]:
sum2=sum.round(decimals=4)
sum2

array([[16.+0.j,  0.+0.j,  0.-0.j,  0.+0.j],
       [ 0.+0.j, 16.+0.j,  0.+0.j,  0.-0.j],
       [ 0.+0.j,  0.+0.j, 16.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j, 16.+0.j]])